language: r
r:
  - oldrel
  - release
  - devel
#sudo: required
warnings_are_errors: true
r_packages:
  - DiceKriging
  - DiceEval
  - rgl
  - covr
os:
  - linux
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3
after_success:
- Rscript -e 'covr::codecov()'
#- bash <(curl -s https://codecov.io/bash)
