name: submit-CRAN

on:
  push:
    branches: [main, master]
    tags: [ '*.*' ]
  pull_request:
    branches: [main, master]

env:
  DEBUG_CI: true

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - uses: r-lib/actions/setup-r-dependencies@v2

    - name: Install X11 dependencies on MacOS
      if: runner.os == 'macOS'
      run: brew install xquartz

    - run: |
        cd ..; R CMD build DiceView
        mkdir DiceView/CRAN-${{ matrix.os }}
        mv DiceView_*.* DiceView/CRAN-${{ matrix.os }}/.
      shell: bash
      name: R CMD build

    - run: |
        R CMD check --as-cran --no-manual CRAN-${{ matrix.os }}/DiceView* || (
          test -f DiceView.Rcheck/00install.out && cat DiceView.Rcheck/00install.out | sed -e 's/^/00install.out| /';
          exit 1
        )
      shell: bash
      name: R CMD check
    - uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.os }}
        path: ./CRAN-*

    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./CRAN-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
